[build]
  base = "zenzalife-scheduler"
  command = "pnpm run build"
  publish = "dist"

[functions]
  # The build runs from the `zenzalife-scheduler` subdirectory. Use a
  # relative path so Netlify can locate the serverless functions stored
  # at the repository root.
  directory = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

