[build]
  base = "zenzalife-scheduler"
  command = "pnpm run build"
publish = "dist"

[functions]
  directory = "netlify/functions"

[functions]
  directory = "netlify/functions"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
