[build]
  base = "zenzalife-scheduler"
  command = "pnpm run build"
  publish = "dist"

[functions]
  # Path is relative to the build base directory so we go up one level
  directory = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

