[build]
  base = "zenzalife-scheduler"
  # Install root dependencies so functions have their node modules
  command = "pnpm --dir .. install && pnpm run build"
  publish = "dist"

[build.environment]
  # Ignore the test Firebase key bundled with Excalidraw so Netlify's
  # secrets scanner doesn't flag it as a leaked credential
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza"

[functions]
  # The build runs from the `zenzalife-scheduler` subdirectory. Use a
  # relative path so Netlify can locate the serverless functions stored
  # at the repository root.
  directory = "../netlify/functions"
  # Bundle all dependencies with the functions to avoid missing modules

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

