[build]
  base = "zenzalife-scheduler"
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_SERVICE_ROLE_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
