CREATE TABLE children_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL,
    user_id UUID,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(100),
    gender VARCHAR(50),
    birthdate DATE,
    age INTEGER,
    profile_photo TEXT,
    current_school VARCHAR(255),
    grade_year VARCHAR(100),
    school_start DATE,
    dream_school VARCHAR(255),
    school_aspirations TEXT,
    dreams_goals TEXT,
    hobbies TEXT,
    parent_notes TEXT,
    milestones JSONB DEFAULT '[]',
    academic_progress JSONB DEFAULT '{}',
    progress_score INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);